# Exynos 9810: Droidian schedtune'un mount olmamasini gerektiriyor.
# Bazi cihaz kernelleri sikayet ettigi icin boot sirasinda umount ediyoruz.
[Service]
ExecStartPre=-/usr/bin/umount -l /sys/fs/cgroup/schedtune
